export const setStateType = {
    INIT_STATE :'INIT_STATE',
    SET_USER: 'SET_USER',
    SET_CART: 'SET_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    INCREASE_CART_ITEM: 'INCREASE_CART_ITEM',
    DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
    REMOVE_FROM_CART: 'REMOVE_ITEM_FROM_CART',
};